spring:
  application:
    name: 'auth-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_CLUSTER}/${MONGODB_DATABASE}?retryWrites=true&w=majority&appName=${MONGODB_APP_NAME}'

jwt.secret: ${JWT_SECRET}
jwt.expiration: ${JWT_EXPIRATION}
jwt.expiration-seconds.refresh-token: ${JWT_EXPIRATION_SECONDS_REFRESH_TOKEN}

eureka:
  client:
    service-url:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

server:
  port: ${SERVER_PORT:8082}
