spring:
  application:
    name: 'order-service-api'
  jpa:
    hibernate:
      ddl-auto: 'create'
  datasource:
    url: '${DATASOURCE_URL}'
    username: '${DATASOURCE_USERNAME}'
    password: '${DATASOURCE_PASSWORD}'
    driver-class-name: '${DATASOURCE_DRIVER_CLASS_NAME}'
    hikari:
      connection-timeout: 20000
springdoc:
  open-api:
    info:
      title: 'Order Service API'
      description: 'API responsible for managing orders'
      version: '1.0.0'
server:
  port: ${SERVER_PORT:8100}
